name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: flutter

      - name: Build Windows EXE
        run: flutter build windows --release
        working-directory: flutter

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: CyberDesk-Windows-EXE
          path: flutter/build/windows/runner/Release
