name: Build CyberDesk Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Windows executable
        run: flutter build windows --release

      - name: Upload Windows executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: CyberDesk-Windows-Release
          path: build/windows/runner/Release/CyberDesk.exe
