name: Build CyberDesk Windows

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      target:
        type: string
        default: windows-latest

jobs:
  build:
    runs-on: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Build Rust release
        run: cargo build --release

      - name: Upload artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v3
        with:
          name: cyberdesk-rust-release
          path: target/release/cyberdesk.exe
